name: Cosign
description: Cosign plugin for BuildKite
author: Hari
requirements:
  - bash
  - uname
  - curl
  - mktemp
configuration:
  properties:
    image: 
      type: string
      description: "The container image tag to sign"
    keyless: 
      type: boolean
      description: "Use keyless signing"
      default: false
    keyless-config:
      type: object
      properties:
        fulcio-url:
          type: string
          description: "Fulcio URL"
          default: "https://fulcio.sigstore.dev"
        rekor-url:
          type: string
          description: "Rekor URL"
          default: "https://rekor.sigstore.dev"
        oidc-issuer:
          type: string
          description: "OIDC issuer"
        oidc-provider:
          type: string
          description: "OIDC provider"
          default: "github"
    keyed-config:
      type: object
      properties:
        key:
          type: string
          description: "Signing key path"
    cosign-version:
      type: string
      description: "The version of cosign to use"
  required:
    - image
  additionalProperties: false
