name: Cosign
description: Cosign plugin for Buildkite
author: Equinix Metal
requirements:
  - bash
  - uname
  - curl
  - mktemp
configuration:
  properties:
    image:
      type: string
      description: "The container image tag to sign"
    keyless:
      type: boolean
      description: "Use keyless signing"
      default: true
    keyless-config:
      type: object
      properties:
        tuf-mirror-url:
          type: string
          description: "TUF URL"
        tuf-root-url:
          type: string
          description: "TUF root"
        rekor-url:
          type: string
          description: "Rekor URL"
        fulcio-url:
          type: string
          description: "Fulcio URL"
        oidc-issuer:
          type: string
          description: "OIDC issuer"
        oidc-provider:
          type: string
          description: "OIDC provider"
          default: "buildkite-agent"
        identity-token-env:
          type: string
          description: "Environment variable from which identity token to be read"
        identity-token:
          type: string
          description: "Identity token, this overrides identity-token-env"
    keyed-config:
      type: object
      properties:
        tuf-mirror-url:
          type: string
          description: "TUF URL"
        tuf-root-url:
          type: string
          description: "TUF root"
        rekor-url:
          type: string
          description: "Rekor URL"
        key:
          type: string
          description: "Signing key path"
    cosign-version:
      type: string
      description: "The version of cosign to use"
  required:
    - image
  additionalProperties: false
